import './global.css';

// app/layout.tsx
export const metadata = {
    title: 'My Next.js App',
    description: 'Generated by create-next-app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
